[project]
classifiers = ["Private :: Do Not Upload"]
name = "glmbf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax>=0.7.0",
    "numpy>=2.3.2",
    "optax>=0.2.5",
    "pandas>=2.3.1",
]
